var namespacecopads_1_1copadsexceptions =
[
    [ "ArrayError", "de/d6a/classcopads_1_1copadsexceptions_1_1_array_error.html", "de/d6a/classcopads_1_1copadsexceptions_1_1_array_error" ],
    [ "CopadsError", "d3/da1/classcopads_1_1copadsexceptions_1_1_copads_error.html", null ],
    [ "DistanceError", "d4/d7c/classcopads_1_1copadsexceptions_1_1_distance_error.html", null ],
    [ "DistanceInputSizeError", "dd/d50/classcopads_1_1copadsexceptions_1_1_distance_input_size_error.html", "dd/d50/classcopads_1_1copadsexceptions_1_1_distance_input_size_error" ],
    [ "DistributionError", "d4/d3e/classcopads_1_1copadsexceptions_1_1_distribution_error.html", null ],
    [ "DistributionFunctionError", "d4/d9a/classcopads_1_1copadsexceptions_1_1_distribution_function_error.html", "d4/d9a/classcopads_1_1copadsexceptions_1_1_distribution_function_error" ],
    [ "DistributionParameterError", "d6/d21/classcopads_1_1copadsexceptions_1_1_distribution_parameter_error.html", "d6/d21/classcopads_1_1copadsexceptions_1_1_distribution_parameter_error" ],
    [ "EdgeNotFoundError", "d6/d72/classcopads_1_1copadsexceptions_1_1_edge_not_found_error.html", "d6/d72/classcopads_1_1copadsexceptions_1_1_edge_not_found_error" ],
    [ "FunctionParameterTypeError", "d8/d4a/classcopads_1_1copadsexceptions_1_1_function_parameter_type_error.html", "d8/d4a/classcopads_1_1copadsexceptions_1_1_function_parameter_type_error" ],
    [ "FunctionParameterValueError", "da/d44/classcopads_1_1copadsexceptions_1_1_function_parameter_value_error.html", "da/d44/classcopads_1_1copadsexceptions_1_1_function_parameter_value_error" ],
    [ "GraphEdgeSizeMismatchError", "d6/d24/classcopads_1_1copadsexceptions_1_1_graph_edge_size_mismatch_error.html", "d6/d24/classcopads_1_1copadsexceptions_1_1_graph_edge_size_mismatch_error" ],
    [ "GraphError", "dc/d3d/classcopads_1_1copadsexceptions_1_1_graph_error.html", null ],
    [ "GraphParameterError", "df/d6d/classcopads_1_1copadsexceptions_1_1_graph_parameter_error.html", "df/d6d/classcopads_1_1copadsexceptions_1_1_graph_parameter_error" ],
    [ "MatrixAdditionError", "de/d4f/classcopads_1_1copadsexceptions_1_1_matrix_addition_error.html", "de/d4f/classcopads_1_1copadsexceptions_1_1_matrix_addition_error" ],
    [ "MatrixArithmeticError", "da/d72/classcopads_1_1copadsexceptions_1_1_matrix_arithmetic_error.html", "da/d72/classcopads_1_1copadsexceptions_1_1_matrix_arithmetic_error" ],
    [ "MatrixDeterminantError", "d6/dcc/classcopads_1_1copadsexceptions_1_1_matrix_determinant_error.html", "d6/dcc/classcopads_1_1copadsexceptions_1_1_matrix_determinant_error" ],
    [ "MatrixError", "db/dd0/classcopads_1_1copadsexceptions_1_1_matrix_error.html", null ],
    [ "MatrixMinorError", "d3/d6a/classcopads_1_1copadsexceptions_1_1_matrix_minor_error.html", "d3/d6a/classcopads_1_1copadsexceptions_1_1_matrix_minor_error" ],
    [ "MatrixMultiplicationError", "d1/d97/classcopads_1_1copadsexceptions_1_1_matrix_multiplication_error.html", "d1/d97/classcopads_1_1copadsexceptions_1_1_matrix_multiplication_error" ],
    [ "MatrixSquareError", "d2/d54/classcopads_1_1copadsexceptions_1_1_matrix_square_error.html", "d2/d54/classcopads_1_1copadsexceptions_1_1_matrix_square_error" ],
    [ "MatrixTraceError", "d6/d87/classcopads_1_1copadsexceptions_1_1_matrix_trace_error.html", "d6/d87/classcopads_1_1copadsexceptions_1_1_matrix_trace_error" ],
    [ "MaxIterationsException", "d9/d56/classcopads_1_1copadsexceptions_1_1_max_iterations_exception.html", null ],
    [ "NormalDistributionTypeError", "de/da4/classcopads_1_1copadsexceptions_1_1_normal_distribution_type_error.html", "de/da4/classcopads_1_1copadsexceptions_1_1_normal_distribution_type_error" ],
    [ "NotAdjacencyGraphMatrixError", "db/dba/classcopads_1_1copadsexceptions_1_1_not_adjacency_graph_matrix_error.html", "db/dba/classcopads_1_1copadsexceptions_1_1_not_adjacency_graph_matrix_error" ],
    [ "StatisticsError", "df/d0f/classcopads_1_1copadsexceptions_1_1_statistics_error.html", null ],
    [ "TreeError", "d0/d64/classcopads_1_1copadsexceptions_1_1_tree_error.html", null ],
    [ "TreeNodeTypeError", "d0/d1c/classcopads_1_1copadsexceptions_1_1_tree_node_type_error.html", "d0/d1c/classcopads_1_1copadsexceptions_1_1_tree_node_type_error" ],
    [ "UnknownGraphMatrixError", "dc/d78/classcopads_1_1copadsexceptions_1_1_unknown_graph_matrix_error.html", "dc/d78/classcopads_1_1copadsexceptions_1_1_unknown_graph_matrix_error" ],
    [ "VertexNotFoundError", "df/d5d/classcopads_1_1copadsexceptions_1_1_vertex_not_found_error.html", "df/d5d/classcopads_1_1copadsexceptions_1_1_vertex_not_found_error" ]
];